spring:
  datasource:
    url: jdbc:h2:mem:spring;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

