spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none